
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yan Revuz
 */
public class ExerciceFeuTricolore extends javax.swing.JFrame {
    
    //Tous les etat de notre Automate
    private enum State {
        ARRET, //etat initial
        ROUGE,
        VERT,
        ORANGE,
        ORANGE_ALLUME,
        ETIENT
    }
    
    
    /* Etat en cours*/
    private State etatEnCours;
    
    /* Represente la fréquence d'un tic du timer rouge */
    private static final int DELAY_TIMER_RED = 2000;
    
    /* Le timer du feu rouge de notre application */
    private Timer redTimer;
    
    /* Represente la fréquence d'un tic du timer vert */
    private static final int DELAY_TIMER_VERT = 3000;
    
    /* Le timer du feu vert de notre application */
    private Timer greenTimer;
    
    /* Represente la fréquence d'un tic du timer orange */
    private static final int DELAY_TIMER_ORANGE = 1500;
    
    /* Le timer du feu orange de notre application */
    private Timer orangeTimer;
    
    /* Represente la fréquence d'un tic du timer panne Allume */
    private static final int DELAY_TIMER_PAUSE_ON = 1000;
    
    /* Le timer du feu orange en panne allume de notre application */
    private Timer panneOnTimer;
    
    /* Represente la fréquence d'un tic du timer panne Eteint */
    private static final int DELAY_TIMER_PAUSE_OFF = 500;
    
    /* Le timer du feu orange en panne eteint de notre application */
    private Timer panneOffTimer;
    
    /**
     * Creates new form ExerciceFeuTricolore
     */
    public ExerciceFeuTricolore() {
        initComponents();
        init();
    }
    
    public void init(){
        this.redTimer = new Timer(DELAY_TIMER_RED, taskPerformerRed);
        this.greenTimer = new Timer(DELAY_TIMER_VERT, taskPerformerGreen);
        this.orangeTimer = new Timer(DELAY_TIMER_ORANGE, taskPerformerOrange);
        this.panneOnTimer = new Timer(DELAY_TIMER_PAUSE_ON, taskPerformerPanneOn);
        this.panneOffTimer = new Timer(DELAY_TIMER_PAUSE_OFF, taskPerformerPanneOff);
        setEnabledOnButton(true);
        setEnabledOffButton(false);
        setEnabledPauseButton(false);
        changeState(State.ARRET);
    }
    
    /* Permet de desactiver / activer le boutton marche*/
    public void setEnabledOnButton(boolean enabled){
        this.onButton.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton arret */
    public void setEnabledOffButton(boolean enabled){
        this.offButton.setEnabled(enabled);
    }
    
    /* Permet de desactiver / activer le boutton pause */
    public void setEnabledPauseButton(boolean enabled){
        this.pauseButton.setEnabled(enabled);
    }
    
     /* Permet de changer d'état */
    public void changeState(State state){
        this.etatEnCours = state;
    }
    
    /* Permet de demarrer le timer rouge */
    public void startRedTimer(){
        this.redTimer.start();
    }
    
    /* Permet d'interrompre le timer rouge */
    public void stopRedTimer(){
        this.redTimer.stop();
    }
    
    /* Permet de demarrer le timer vert */
    public void startGreenTimer(){
        this.greenTimer.start();
    }
    
    /* Permet d'interrompre le timer vert */
    public void stopGreenTimer(){
        this.greenTimer.stop();
    
    } 
    
    /* Permet de demarrer le timer orange */
    public void startOrangeTimer(){
        this.orangeTimer.start();
    }
    
    /* Permet d'interrompre le timer orange */
    public void stopOrangeTimer(){
        this.orangeTimer.stop();
    }  
    
    /* Permet de demarrer le timer pauseOn */
    public void startPauseOnTimer(){
        this.panneOnTimer.start();
    }
    
    /* Permet d'interrompre le timer pauseOn */
    public void stopPauseOnTimer(){
        this.panneOnTimer.stop();
    }
    
    /* Permet de demarrer le timer pauseOff */
    public void startPauseOffTimer(){
        this.panneOffTimer.start();
    }
    
    /* Permet d'interrompre le timer pauseOff */
    public void stopPauseOffTimer(){
        this.panneOffTimer.stop();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        offButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        onButton.setText("Marche");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        offButton.setText("Arrêt");
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(onButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(onButton)
                .addGap(50, 50, 50)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(offButton)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        setEnabledOnButton(false);
                setEnabledOffButton(true);
                setEnabledPauseButton(true);
        switch(etatEnCours){
            case ARRET:
                changeState(State.ROUGE);
                startRedTimer();
                repaint();
                break;
            case ROUGE:
                /* Interdit */
                break;
            case ORANGE:
                /* Interdit */
                break;
            case VERT:
                /* Interdit */
                break;
            case ORANGE_ALLUME:
                changeState(State.ROUGE);
                stopPauseOnTimer();
                startRedTimer();
                repaint();
                break;
            case ETIENT:
                changeState(State.ROUGE);
                stopPauseOffTimer();
                startRedTimer();
                repaint();
                break;    
        }
    }//GEN-LAST:event_onButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        setEnabledOnButton(true);
        setEnabledOffButton(true);
        setEnabledPauseButton(false);
        switch(etatEnCours){
            case ARRET:
                /* Interdit */
                break;
            case ROUGE:
                changeState(State.ETIENT);
                stopRedTimer();
                startPauseOffTimer();
                repaint();
                break;
            case ORANGE:
                changeState(State.ETIENT
                );
                stopOrangeTimer();
                startPauseOffTimer();
                repaint();
                break;
            case VERT:
                changeState(State.ETIENT);
                stopGreenTimer();
                startPauseOffTimer();
                repaint();
                break;
            case ORANGE_ALLUME:
                /* Interdit */
                break;
            case ETIENT:
                /* Interdit */
                break;    
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
        setEnabledOnButton(true);
        setEnabledOffButton(false);
        setEnabledPauseButton(false);
        switch(etatEnCours){
            case ARRET:
                /* Interdit */
                break;
            case ROUGE:
                changeState(State.ARRET);
                stopRedTimer();
                repaint();
                break;
            case ORANGE:
                changeState(State.ARRET);
                stopOrangeTimer();
                repaint();
                break;
            case VERT:
                changeState(State.ARRET);
                stopGreenTimer();
                repaint();
                break;
            case ORANGE_ALLUME:
                changeState(State.ARRET);
                stopPauseOnTimer();
                repaint();
                break;
            case ETIENT:
                changeState(State.ARRET);
                stopPauseOffTimer();
                repaint();
                break;    
        }
    }//GEN-LAST:event_offButtonActionPerformed
    
    /* Déclaration des action réalisées lors d'un tic du timer rouge */
    ActionListener taskPerformerRed = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            switch(etatEnCours){
                case ARRET:
                    /* Interdit */
                    break;
                case ROUGE:
                    changeState(State.VERT);
                    stopRedTimer();
                    startGreenTimer();
                    repaint();
                    break;
                case ORANGE:
                    /* Interdit */
                    break;
                case VERT:
                    /* Interdit */
                    break;
                case ORANGE_ALLUME:
                    /* Interdit */
                    break;
                case ETIENT:
                    /* Interdit */
                    break;    
            }
        }
    };
    
    /* Déclaration des action réalisées lors d'un tic du timer vert */
    ActionListener taskPerformerGreen = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            switch(etatEnCours){
                case ARRET:
                    /* Interdit */
                    break;
                case ROUGE:
                    /* Interdit */
                    break;
                case ORANGE:
                    /* Interdit */
                    break;
                case VERT:
                    changeState(State.ORANGE);
                    stopGreenTimer();
                    startOrangeTimer();
                    repaint();
                    break;
                case ORANGE_ALLUME:
                    /* Interdit */
                    break;
                case ETIENT:
                    /* Interdit */
                    break;    
            }
        }
    };
    
    /* Déclaration des action réalisées lors d'un tic du timer orange */
    ActionListener taskPerformerOrange = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            switch(etatEnCours){
                case ARRET:
                    /* Interdit */
                    break;
                case ROUGE:
                    /* Interdit */
                    break;
                case ORANGE:
                    changeState(State.ROUGE);
                    stopOrangeTimer();
                    startRedTimer();
                    repaint();
                    break;
                case VERT:
                    /* Interdit */
                    break;
                case ORANGE_ALLUME:
                    /* Interdit */
                    break;
                case ETIENT:
                    /* Interdit */
                    break;    
            }
        }
    };
    
    /* Déclaration des action réalisées lors d'un tic du timer panneOn */
    ActionListener taskPerformerPanneOn = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            switch(etatEnCours){
                case ARRET:
                    /* Interdit */
                    break;
                case ROUGE:
                    /* Interdit */
                    break;
                case ORANGE:
                    /* Interdit */
                    break;
                case VERT:
                    /* Interdit */
                    break;
                case ORANGE_ALLUME:
                    changeState(State.ETIENT);
                    stopPauseOnTimer();
                    startPauseOffTimer();
                    repaint();
                    break;
                case ETIENT:
                    /* Interdit */
                    break;    
            }
        }
    };
    
    /* Déclaration des action réalisées lors d'un tic du timer panneOff */
    ActionListener taskPerformerPanneOff = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            switch(etatEnCours){
                case ARRET:
                    /* Interdit */
                    break;
                case ROUGE:
                    /* Interdit */
                    break;
                case ORANGE:
                    /* Interdit */
                    break;
                case VERT:
                    /* Interdit */
                    break;
                case ORANGE_ALLUME:
                    /* Interdit */
                    break;
                case ETIENT:
                    changeState(State.ORANGE_ALLUME);
                    stopPauseOffTimer();
                    startPauseOnTimer();
                    repaint();
                    break;    
            }
        }
    };
    
    public void rougeOn(Graphics g){
        g.setColor(Color.RED);
        g.fillOval( 200, 60, 50, 50 );
        g.setColor(Color.BLACK);
        g.drawOval(200, 150, 50, 50);
        g.drawOval(200, 240, 50, 50);  
    }
    
    public void vertOn(Graphics g){
        g.setColor(Color.GREEN);
        g.fillOval(200, 240, 50, 50);  
        g.setColor(Color.BLACK);
        g.drawOval( 200, 60, 50, 50 );
        g.drawOval(200, 150, 50, 50);   
    }
    
    public void orangeOn(Graphics g){
        g.setColor(Color.ORANGE);
        g.fillOval(200, 150, 50, 50);
        g.setColor(Color.BLACK);
        g.drawOval( 200, 60, 50, 50 );
        g.drawOval(200, 240, 50, 50);  
    }
    
    public void allEteint(Graphics g){
        g.setColor(Color.BLACK);
        g.drawOval( 200, 60, 50, 50 );
        g.drawOval(200, 150, 50, 50);
        g.drawOval(200, 240, 50, 50);  
    }
    
    public void paint(Graphics g) {
        super.paint(g);
        switch(etatEnCours){
            case ARRET:
                allEteint(g);
                break;
            case ROUGE:
                rougeOn(g);
                break;
            case ORANGE:
                orangeOn(g);
                break;
            case VERT:
                vertOn(g);
                break;
            case ORANGE_ALLUME:
                orangeOn(g);
                break;
            case ETIENT:
                allEteint(g);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciceFeuTricolore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciceFeuTricolore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciceFeuTricolore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciceFeuTricolore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciceFeuTricolore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton offButton;
    private javax.swing.JButton onButton;
    private javax.swing.JButton pauseButton;
    // End of variables declaration//GEN-END:variables
}
